### ISSUE TITLE
clang-format entire repo?

### ISSUE THREAD

**Issue by davetcoleman** [RethinkRobotics/baxter_simulator#103]
Would it be ok if I ran the roscpp style guideline-based clang-formater we use for MoveIt! on this repo also? I'm digging into the code and having a hard time not fixing all the inconsistencies I'm seeing.

**Comment by davetcoleman** [comment]
I couldn't help myself... https://github.com/RethinkRobotics/baxter_simulator/pull/104

**Comment by IanTheEngineer** [comment]
Resolved by #104
