### ISSUE TITLE
VELOCITY_MODE is not followed correctly on joints 4 to 7

### ISSUE THREAD

**Issue by ghost** [RethinkRobotics/baxter_simulator#59]
From Unige on the brr-users group:
"I was playing around with the simulator and initially, till I was using POSITION_MODE to control the joints everything was fine.
Then when I tried to switch to VELOCITY_MODE I noticed that from joint 4 to 7 the velocity is not followed correctly, and only for mid-high velocities (2 to 6 r/s) you can see the joint moving.
I thought it was a problem of my implementation but I tried on the real Baxter and everything was working correctly."

Details on how to reproduce this issue to follow.

**Comment by xli4217** [comment]
I'm recently struggling with the same problem for all the joints. Even commanding all joint velocities to be zero fails in the simulator. Help would be much appreciated. Thanks.
