### ISSUE TITLE
Unable to install baxter simulator. Ros: Indigo OS: Ubuntu 14:04

### ISSUE THREAD

**Issue by mjm522** [RethinkRobotics/baxter_simulator#89]
I tried installing baxter simulator several times, but keep getting this error always. I tried deleting the devel folder and started from the beginning, but with no progress. Can anybody please tell me what I doing wrong? 

`/usr/local/include/urdf_model/types.h:62:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(JointMimic);
 ^
/usr/local/include/urdf_model/types.h:62:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(JointMimic);
 ^
/usr/local/include/urdf_model/types.h:63:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(JointSafety);
 ^
/usr/local/include/urdf_model/types.h:63:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(JointSafety);
 ^
/usr/local/include/urdf_model/types.h:63:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(JointSafety);
 ^
/usr/local/include/urdf_model/types.h:64:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Link);
 ^
/usr/local/include/urdf_model/types.h:64:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Link);
 ^
/usr/local/include/urdf_model/types.h:64:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Link);
 ^
/usr/local/include/urdf_model/types.h:65:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Material);
 ^
/usr/local/include/urdf_model/types.h:65:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Material);
 ^
/usr/local/include/urdf_model/types.h:65:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Material);
 ^
/usr/local/include/urdf_model/types.h:66:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Mesh);
 ^
/usr/local/include/urdf_model/types.h:66:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Mesh);
 ^
/usr/local/include/urdf_model/types.h:66:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Mesh);
 ^
/usr/local/include/urdf_model/types.h:67:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Sphere);
 ^
/usr/local/include/urdf_model/types.h:67:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Sphere);
 ^
/usr/local/include/urdf_model/types.h:67:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Sphere);
 ^
/usr/local/include/urdf_model/types.h:68:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Visual);
 ^
/usr/local/include/urdf_model/types.h:68:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Visual);
 ^
/usr/local/include/urdf_model/types.h:68:1: error: ‘weak_ptr’ in namespace ‘std’ does not name a type
 URDF_TYPEDEF_CLASS_POINTER(Visual);
 ^
/usr/local/include/urdf_model/types.h:72:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 std::shared_ptr<T> const_pointer_cast(std::shared_ptr<U> const & r)
 ^
/usr/local/include/urdf_model/types.h:78:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 std::shared_ptr<T> dynamic_pointer_cast(std::shared_ptr<U> const & r)
 ^
/usr/local/include/urdf_model/types.h:84:1: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 std::shared_ptr<T> static_pointer_cast(std::shared_ptr<U> const & r)
 ^
In file included from /usr/local/include/urdf_model/link.h:44:0,
                 from /usr/local/include/urdf_model/model.h:42,
                 from /opt/ros/indigo/include/urdf/model.h:42,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/joint.h:141:3: error: ‘DoubleSharedPtr’ does not name a type
   DoubleSharedPtr rising, falling;
   ^
/usr/local/include/urdf_model/joint.h:199:3: error: ‘JointDynamicsSharedPtr’ does not name a type
   JointDynamicsSharedPtr dynamics;
   ^
/usr/local/include/urdf_model/joint.h:202:3: error: ‘JointLimitsSharedPtr’ does not name a type
   JointLimitsSharedPtr limits;
   ^
/usr/local/include/urdf_model/joint.h:205:3: error: ‘JointSafetySharedPtr’ does not name a type
   JointSafetySharedPtr safety;
   ^
/usr/local/include/urdf_model/joint.h:208:3: error: ‘JointCalibrationSharedPtr’ does not name a type
   JointCalibrationSharedPtr calibration;
   ^
/usr/local/include/urdf_model/joint.h:211:3: error: ‘JointMimicSharedPtr’ does not name a type
   JointMimicSharedPtr mimic;
   ^
/usr/local/include/urdf_model/joint.h: In member function ‘void urdf::Joint::clear()’:
/usr/local/include/urdf_model/joint.h:219:11: error: ‘class urdf::Joint’ has no member named ‘dynamics’
     this->dynamics.reset();
           ^
/usr/local/include/urdf_model/joint.h:220:11: error: ‘class urdf::Joint’ has no member named ‘limits’
     this->limits.reset();
           ^
/usr/local/include/urdf_model/joint.h:221:11: error: ‘class urdf::Joint’ has no member named ‘safety’
     this->safety.reset();
           ^
/usr/local/include/urdf_model/joint.h:222:11: error: ‘class urdf::Joint’ has no member named ‘calibration’
     this->calibration.reset();
           ^
/usr/local/include/urdf_model/joint.h:223:11: error: ‘class urdf::Joint’ has no member named ‘mimic’
     this->mimic.reset();
           ^
In file included from /usr/local/include/urdf_model/link.h:45:0,
                 from /usr/local/include/urdf_model/model.h:42,
                 from /opt/ros/indigo/include/urdf/model.h:42,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/color.h: In member function ‘bool urdf::Color::init(const string&)’:
/usr/local/include/urdf_model/color.h:76:26: error: ‘stof’ is not a member of ‘std’
           rgba.push_back(std::stof(pieces[i]));
                          ^
In file included from /usr/local/include/urdf_model/model.h:42:0,
                 from /opt/ros/indigo/include/urdf/model.h:42,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/link.h: At global scope:
/usr/local/include/urdf_model/link.h:152:3: error: ‘GeometrySharedPtr’ does not name a type
   GeometrySharedPtr geometry;
   ^
/usr/local/include/urdf_model/link.h:155:3: error: ‘MaterialSharedPtr’ does not name a type
   MaterialSharedPtr material;
   ^
/usr/local/include/urdf_model/link.h: In member function ‘void urdf::Visual::clear()’:
/usr/local/include/urdf_model/link.h:161:5: error: ‘material’ was not declared in this scope
     material.reset();
     ^
/usr/local/include/urdf_model/link.h:162:5: error: ‘geometry’ was not declared in this scope
     geometry.reset();
     ^
/usr/local/include/urdf_model/link.h: At global scope:
/usr/local/include/urdf_model/link.h:174:3: error: ‘GeometrySharedPtr’ does not name a type
   GeometrySharedPtr geometry;
   ^
/usr/local/include/urdf_model/link.h: In member function ‘void urdf::Collision::clear()’:
/usr/local/include/urdf_model/link.h:179:5: error: ‘geometry’ was not declared in this scope
     geometry.reset();
     ^
/usr/local/include/urdf_model/link.h: At global scope:
/usr/local/include/urdf_model/link.h:196:3: error: ‘InertialSharedPtr’ does not name a type
   InertialSharedPtr inertial;
   ^
/usr/local/include/urdf_model/link.h:199:3: error: ‘VisualSharedPtr’ does not name a type
   VisualSharedPtr visual;
   ^
/usr/local/include/urdf_model/link.h:202:3: error: ‘CollisionSharedPtr’ does not name a type
   CollisionSharedPtr collision;
   ^
In file included from /usr/local/include/urdf_model/model.h:42:0,
                 from /opt/ros/indigo/include/urdf/model.h:42,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/link.h:205:15: error: ‘CollisionSharedPtr’ was not declared in this scope
   std::vector<CollisionSharedPtr> collision_array;
               ^
/usr/local/include/urdf_model/link.h:205:33: error: template argument 1 is invalid
   std::vector<CollisionSharedPtr> collision_array;
                                 ^
/usr/local/include/urdf_model/link.h:205:33: error: template argument 2 is invalid
/usr/local/include/urdf_model/link.h:208:15: error: ‘VisualSharedPtr’ was not declared in this scope
   std::vector<VisualSharedPtr> visual_array;
               ^
/usr/local/include/urdf_model/link.h:208:30: error: template argument 1 is invalid
   std::vector<VisualSharedPtr> visual_array;
                              ^
/usr/local/include/urdf_model/link.h:208:30: error: template argument 2 is invalid
/usr/local/include/urdf_model/link.h:213:3: error: ‘JointSharedPtr’ does not name a type
   JointSharedPtr parent_joint;
   ^
/usr/local/include/urdf_model/link.h:215:15: error: ‘JointSharedPtr’ was not declared in this scope
   std::vector<JointSharedPtr> child_joints;
               ^
/usr/local/include/urdf_model/link.h:215:29: error: template argument 1 is invalid
   std::vector<JointSharedPtr> child_joints;
                             ^
/usr/local/include/urdf_model/link.h:215:29: error: template argument 2 is invalid
/usr/local/include/urdf_model/link.h:216:15: error: ‘LinkSharedPtr’ was not declared in this scope
   std::vector<LinkSharedPtr> child_links;
               ^
/usr/local/include/urdf_model/link.h:216:28: error: template argument 1 is invalid
   std::vector<LinkSharedPtr> child_links;
                            ^
/usr/local/include/urdf_model/link.h:216:28: error: template argument 2 is invalid
/usr/local/include/urdf_model/link.h:218:3: error: ‘LinkSharedPtr’ does not name a type
   LinkSharedPtr getParent() const
   ^
/usr/local/include/urdf_model/link.h:221:24: error: ‘LinkSharedPtr’ does not name a type
   void setParent(const LinkSharedPtr &parent)
                        ^
/usr/local/include/urdf_model/link.h:238:3: error: ‘LinkWeakPtr’ does not name a type
   LinkWeakPtr parent_link_;
   ^
/usr/local/include/urdf_model/link.h: In member function ‘void urdf::Link::setParent(const int&)’:
/usr/local/include/urdf_model/link.h:222:5: error: ‘parent_link_’ was not declared in this scope
   { parent_link_ = parent; }
     ^
/usr/local/include/urdf_model/link.h: In member function ‘void urdf::Link::clear()’:
/usr/local/include/urdf_model/link.h:227:11: error: ‘class urdf::Link’ has no member named ‘inertial’
     this->inertial.reset();
           ^
/usr/local/include/urdf_model/link.h:228:11: error: ‘class urdf::Link’ has no member named ‘visual’
     this->visual.reset();
           ^
/usr/local/include/urdf_model/link.h:229:11: error: ‘class urdf::Link’ has no member named ‘collision’
     this->collision.reset();
           ^
/usr/local/include/urdf_model/link.h:230:11: error: ‘class urdf::Link’ has no member named ‘parent_joint’
     this->parent_joint.reset();
           ^
/usr/local/include/urdf_model/link.h:231:24: error: request for member ‘clear’ in ‘((urdf::Link*)this)->urdf::Link::child_joints’, which is of non-class type ‘int’
     this->child_joints.clear();
                        ^
/usr/local/include/urdf_model/link.h:232:23: error: request for member ‘clear’ in ‘((urdf::Link*)this)->urdf::Link::child_links’, which is of non-class type ‘int’
     this->child_links.clear();
                       ^
/usr/local/include/urdf_model/link.h:233:27: error: request for member ‘clear’ in ‘((urdf::Link*)this)->urdf::Link::collision_array’, which is of non-class type ‘int’
     this->collision_array.clear();
                           ^
/usr/local/include/urdf_model/link.h:234:24: error: request for member ‘clear’ in ‘((urdf::Link*)this)->urdf::Link::visual_array’, which is of non-class type ‘int’
     this->visual_array.clear();
                        ^
In file included from /opt/ros/indigo/include/urdf/model.h:42:0,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/model.h: At global scope:
/usr/local/include/urdf_model/model.h:51:3: error: ‘LinkConstSharedPtr’ does not name a type
   LinkConstSharedPtr getRoot(void) const{return this->root_link_;};
   ^
/usr/local/include/urdf_model/model.h:52:3: error: ‘LinkConstSharedPtr’ does not name a type
   LinkConstSharedPtr getLink(const std::string& name) const
   ^
/usr/local/include/urdf_model/model.h:62:3: error: ‘JointConstSharedPtr’ does not name a type
   JointConstSharedPtr getJoint(const std::string& name) const
   ^
/usr/local/include/urdf_model/model.h:74:29: error: ‘LinkSharedPtr’ was not declared in this scope
   void getLinks(std::vector<LinkSharedPtr >& links) const
                             ^
/usr/local/include/urdf_model/model.h:74:43: error: template argument 1 is invalid
   void getLinks(std::vector<LinkSharedPtr >& links) const
                                           ^
/usr/local/include/urdf_model/model.h:74:43: error: template argument 2 is invalid
/usr/local/include/urdf_model/model.h:92:41: error: ‘LinkSharedPtr’ has not been declared
   void getLink(const std::string& name, LinkSharedPtr &link) const
                                         ^
/usr/local/include/urdf_model/model.h:103:3: error: ‘MaterialSharedPtr’ does not name a type
   MaterialSharedPtr getMaterial(const std::string& name) const
   ^
In file included from /opt/ros/indigo/include/urdf/model.h:42:0,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/model.h:188:25: error: ‘LinkSharedPtr’ was not declared in this scope
   std::map<std::string, LinkSharedPtr> links_;
                         ^
/usr/local/include/urdf_model/model.h:188:38: error: template argument 2 is invalid
   std::map<std::string, LinkSharedPtr> links_;
                                      ^
/usr/local/include/urdf_model/model.h:188:38: error: template argument 4 is invalid
/usr/local/include/urdf_model/model.h:190:25: error: ‘JointSharedPtr’ was not declared in this scope
   std::map<std::string, JointSharedPtr> joints_;
                         ^
/usr/local/include/urdf_model/model.h:190:39: error: template argument 2 is invalid
   std::map<std::string, JointSharedPtr> joints_;
                                       ^
/usr/local/include/urdf_model/model.h:190:39: error: template argument 4 is invalid
/usr/local/include/urdf_model/model.h:192:25: error: ‘MaterialSharedPtr’ was not declared in this scope
   std::map<std::string, MaterialSharedPtr> materials_;
                         ^
/usr/local/include/urdf_model/model.h:192:42: error: template argument 2 is invalid
   std::map<std::string, MaterialSharedPtr> materials_;
                                          ^
/usr/local/include/urdf_model/model.h:192:42: error: template argument 4 is invalid
/usr/local/include/urdf_model/model.h:198:3: error: ‘LinkSharedPtr’ does not name a type
   LinkSharedPtr root_link_;
   ^
In file included from /opt/ros/indigo/include/urdf/model.h:42:0,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/model.h: In member function ‘void urdf::ModelInterface::getLinks(int&) const’:
/usr/local/include/urdf_model/model.h:76:31: error: ‘LinkSharedPtr’ was not declared in this scope
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                               ^
/usr/local/include/urdf_model/model.h:76:44: error: template argument 2 is invalid
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                            ^
/usr/local/include/urdf_model/model.h:76:44: error: template argument 4 is invalid
/usr/local/include/urdf_model/model.h:76:62: error: invalid type in declaration before ‘link’
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                                              ^
/usr/local/include/urdf_model/model.h:76:62: error: expected ‘;’ before ‘link’
/usr/local/include/urdf_model/model.h:76:82: error: request for member ‘begin’ in ‘((const urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘const int’
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                                                                  ^
/usr/local/include/urdf_model/model.h:76:111: error: request for member ‘end’ in ‘((const urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘const int’
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                                                                                               ^
/usr/local/include/urdf_model/model.h:76:116: error: expected ‘)’ before ‘;’ token
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                                                                                                    ^
/usr/local/include/urdf_model/model.h:76:122: error: ISO C++ forbids incrementing a pointer of type ‘int (*)(const char*, const char*)throw ()’ [-fpermissive]
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                                                                                                          ^
/usr/local/include/urdf_model/model.h:76:122: error: lvalue required as increment operand
/usr/local/include/urdf_model/model.h:76:124: error: expected ‘;’ before ‘)’ token
     for (std::map<std::string,LinkSharedPtr>::const_iterator link = this->links_.begin();link != this->links_.end(); link++)
                                                                                                                            ^
/usr/local/include/urdf_model/model.h: In member function ‘void urdf::ModelInterface::clear()’:
/usr/local/include/urdf_model/model.h:85:18: error: request for member ‘clear’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘int’
     this->links_.clear();
                  ^
/usr/local/include/urdf_model/model.h:86:19: error: request for member ‘clear’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::joints_’, which is of non-class type ‘int’
     this->joints_.clear();
                   ^
/usr/local/include/urdf_model/model.h:87:22: error: request for member ‘clear’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::materials_’, which is of non-class type ‘int’
     this->materials_.clear();
                      ^
/usr/local/include/urdf_model/model.h:88:11: error: ‘class urdf::ModelInterface’ has no member named ‘root_link_’
     this->root_link_.reset();
           ^
/usr/local/include/urdf_model/model.h: In member function ‘void urdf::ModelInterface::getLink(const string&, int&) const’:
/usr/local/include/urdf_model/model.h:94:5: error: ‘LinkSharedPtr’ was not declared in this scope
     LinkSharedPtr ptr;
     ^
/usr/local/include/urdf_model/model.h:94:19: error: expected ‘;’ before ‘ptr’
     LinkSharedPtr ptr;
                   ^
/usr/local/include/urdf_model/model.h:95:22: error: request for member ‘find’ in ‘((const urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘const int’
     if (this->links_.find(name) == this->links_.end())
                      ^
/usr/local/include/urdf_model/model.h:95:49: error: request for member ‘end’ in ‘((const urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘const int’
     if (this->links_.find(name) == this->links_.end())
                                                 ^
/usr/local/include/urdf_model/model.h:96:7: error: ‘ptr’ was not declared in this scope
       ptr.reset();
       ^
/usr/local/include/urdf_model/model.h:98:7: error: ‘ptr’ was not declared in this scope
       ptr = this->links_.find(name)->second;
       ^
/usr/local/include/urdf_model/model.h:98:26: error: request for member ‘find’ in ‘((const urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘const int’
       ptr = this->links_.find(name)->second;
                          ^
/usr/local/include/urdf_model/model.h:99:12: error: ‘ptr’ was not declared in this scope
     link = ptr;
            ^
/usr/local/include/urdf_model/model.h: In member function ‘void urdf::ModelInterface::initTree(std::map<std::basic_string<char>, std::basic_string<char> >&)’:
/usr/local/include/urdf_model/model.h:116:32: error: ‘JointSharedPtr’ was not declared in this scope
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                ^
/usr/local/include/urdf_model/model.h:116:46: error: template argument 2 is invalid
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                              ^
/usr/local/include/urdf_model/model.h:116:46: error: template argument 4 is invalid
/usr/local/include/urdf_model/model.h:116:58: error: invalid type in declaration before ‘joint’
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                                          ^
/usr/local/include/urdf_model/model.h:116:58: error: expected ‘;’ before ‘joint’
/usr/local/include/urdf_model/model.h:116:58: error: ‘joint’ was not declared in this scope
/usr/local/include/urdf_model/model.h:116:80: error: request for member ‘begin’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::joints_’, which is of non-class type ‘int’
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                                                                ^
/usr/local/include/urdf_model/model.h:116:111: error: request for member ‘end’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::joints_’, which is of non-class type ‘int’
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                                                                                               ^
/usr/local/include/urdf_model/model.h:116:116: error: expected ‘)’ before ‘;’ token
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                                                                                                    ^
/usr/local/include/urdf_model/model.h:116:118: error: ‘joint’ was not declared in this scope
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                                                                                                      ^
/usr/local/include/urdf_model/model.h:116:125: error: expected ‘;’ before ‘)’ token
     for (std::map<std::string, JointSharedPtr>::iterator joint = this->joints_.begin();joint != this->joints_.end(); joint++)
                                                                                                                             ^
In file included from /opt/ros/indigo/include/urdf/model.h:42:0,
                 from /opt/ros/indigo/include/gazebo_ros_control/robot_hw_sim.h:49,
                 from /opt/ros/indigo/include/gazebo_ros_control/gazebo_ros_control_plugin.h:57,
                 from /home/mjm/baxter_ws/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp:42:
/usr/local/include/urdf_model/model.h:156:3: error: expected ‘}’ at end of input
   }
   ^
/usr/local/include/urdf_model/model.h: In member function ‘void urdf::ModelInterface::initRoot(const std::map<std::basic_string<char>, std::basic_string<char> >&)’:
/usr/local/include/urdf_model/model.h:160:11: error: ‘class urdf::ModelInterface’ has no member named ‘root_link_’
     this->root_link_.reset();
           ^
/usr/local/include/urdf_model/model.h:163:32: error: ‘LinkSharedPtr’ was not declared in this scope
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                ^
/usr/local/include/urdf_model/model.h:163:45: error: template argument 2 is invalid
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                             ^
/usr/local/include/urdf_model/model.h:163:45: error: template argument 4 is invalid
/usr/local/include/urdf_model/model.h:163:63: error: invalid type in declaration before ‘l’
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                                               ^
/usr/local/include/urdf_model/model.h:163:63: error: expected ‘;’ before ‘l’
/usr/local/include/urdf_model/model.h:163:63: error: ‘l’ was not declared in this scope
/usr/local/include/urdf_model/model.h:163:78: error: request for member ‘begin’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘int’
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                                                              ^
/usr/local/include/urdf_model/model.h:163:103: error: request for member ‘end’ in ‘((urdf::ModelInterface*)this)->urdf::ModelInterface::links_’, which is of non-class type ‘int’
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                                                                                       ^
/usr/local/include/urdf_model/model.h:163:108: error: expected ‘)’ before ‘;’ token
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                                                                                            ^
/usr/local/include/urdf_model/model.h:163:110: error: ‘l’ was not declared in this scope
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                                                                                              ^
/usr/local/include/urdf_model/model.h:163:113: error: expected ‘;’ before ‘)’ token
     for (std::map<std::string, LinkSharedPtr>::const_iterator l=this->links_.begin(); l!=this->links_.end(); l++)
                                                                                                                 ^
/usr/local/include/urdf_model/model.h:184:3: error: expected ‘}’ at end of input
   }
   ^
Linking CXX executable /home/mjm/baxter_ws/devel/lib/baxter_sim_io/baxter_sim_io
[ 97%] Built target baxter_sim_io
make[2]: *** [baxter_simulator/baxter_gazebo/CMakeFiles/baxter_gazebo_ros_control.dir/src/baxter_gazebo_ros_control_plugin.cpp.o] Error 1
make[1]: *** [baxter_simulator/baxter_gazebo/CMakeFiles/baxter_gazebo_ros_control.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

**Comment by mjm522** [comment]
What I did: I am interested in simulator version 0.9.1

```
$cd baxter_ws/src/
$git clone https://github.com/RethinkRobotics/baxter_simulator.git
$cd baxter_simulator
$git checkout release-0.9.1
$cd ../../
$source /opt/ros/indigo/setup.bash
$ catkin_make
$ catkin_make install
```

**Comment by mjm522** [comment]
I also tried: the instructions from webpage; with no result.

```
$ cd ~/ros_ws/src
$ wstool init .
$ wstool merge https://raw.githubusercontent.com/RethinkRobotics/baxter_simulator/master/baxter_simulator.rosinstall
$ wstool update
$source /opt/ros/indigo/setup.bash
$ catkin_make
$ catkin_make install
```

**Comment by knorth55** [comment]
@mjm522
have you tried `rosdep install`?
if not, try it after wstool update.

```
cd ~/ros_ws/src
wstool init .
wstool merge https://raw.githubusercontent.com/RethinkRobotics/baxter_simulator/master/baxter_simulator.rosinstall
wstool update
rosdep install --from-path . --ignore-src -y -r
source /opt/ros/indigo/setup.bash
catkin build
```

**Comment by mjm522** [comment]
Thanks for the reply. I get all the same errors are before plus following new errors:

```
Failed     << baxter_sim_kinematics:make             [ Exited with code 2 ]    
Failed    <<< baxter_sim_kinematics                  [ 7.7 seconds ]           
Finished  <<< baxter_sim_io                          [ 8.8 seconds ]           
[build] Summary: 9 of 14 packages succeeded.                                   
[build]   Ignored:   3 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 3 packages were abandoned.                                
[build]   Failed:    2 packages failed.                                        
[build] Runtime: 13.9 seconds total.                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.

```

I am able to isntall packages baxter_common, baxter_interface, baxter_pykdl, baxter, baxter_examples.

But the baxter_simulator doesn't get installed. The errors seem like some C++ compiler fault, like it is not able to resolve some data types. But I don't know where and how to edit to get past this error.

**Comment by knorth55** [comment]
@mjm522 my compiler version is below, and I can compile the package.
try to upgrade your compiler.
and please paste whole output of catkin.

```
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mjm522** [comment]
mine is 

```
$ g++ --version
g++ (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

It is not that issue. I am still trying to figure out.

**Comment by knorth55** [comment]
@mjm522 
according to these FAQ, it seems urdf header file problem.
can you check liburdfdom-headers-dev version?

http://answers.ros.org/question/243756/ros-indigo-install-on-rpi3-urdf-compile-errors/
https://github.com/ros/urdfdom_headers/releases/tag/1.0.0

```
$ dpkg --status liburdfdom-headers-dev
Package: liburdfdom-headers-dev
Status: install ok installed
Priority: extra
Section: libdevel
Installed-Size: 115
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Multi-Arch: foreign
Source: urdfdom-headers
Version: 0.2.3+dfsg-1
Depends: pkg-config
Description: URDF DOM - header files
 The URDF (U-Robot Description Format) library provides core data
 structures and a simple XML parsers for populating the class data
 structures from an URDF file.
 .
 This package contains the headers files.
Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>

```

**Comment by knorth55** [comment]
@mjm522 
i updated liburdfdom-headers-dev to 1.0.0 and i got same error.
I think it is urdfdom-header problem.
my solution is to downgrade urdfdom-headers to 0.4.2.
i use really old urdfdom-headers, but it doesn't matter for my baxter simulation.

**Comment by mjm522** [comment]
Yes, exactly, that fixes the problem. Thanks a lot.  :+1:

**Comment by IanTheEngineer** [comment]
Thanks for your help debugging @knorth55 . Looks like this is a regression in urdfdom-headers

**Comment by knorth55** [comment]
@mjm522 I'm glad to help you :)
@IanTheEngineer you're welcome
